"""
Django settings for SkiOffBounds project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
import dj_database_url  # Importante para Render

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dfs$xcc%m@tjrresj&sf1fn$na&1&njb)v_#ama++ux8_sb@%d'

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto True en local, luego lo cambiamos abajo para producción
DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise para estáticos
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # i18n
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SkiOffBounds.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SkiOffBounds.wsgi.application'

# Base de datos por defecto (SQLite local)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# === INTERNATIONALIZATION (I18N) ===
LANGUAGE_CODE = 'es'

LANGUAGES = [
    ('es', _('Español')),
    ('en', _('English')),
    ('fr', _('Français')),  
    ('it', _('Italiano')),  
    ('de', _('Deutsch')),   
    ('eu', _('Euskera')),   
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# === ARCHIVOS ESTÁTICOS Y MEDIA ===

STATIC_URL = 'static/'
# Donde Django busca estáticos extra (tu carpeta 'static' en la raíz de app)
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'app/static')] 

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración Local de Media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ==========================================
# CONFIGURACIÓN PARA RENDER (PRODUCCIÓN)
# ==========================================
if 'RENDER' in os.environ:
    # 1. Conectar base de datos PostgreSQL de Render
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600)
    }
    
    # 2. Seguridad
    DEBUG = False
    ALLOWED_HOSTS = ['*']
    
    # 3. Configuración WhiteNoise
    # CORRECCIÓN IMPORTANTE: Usamos 'staticfiles' relativo, no '/app/static/' absoluto
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    
    # 4. TRUCO PARA IMÁGENES
    # Le decimos a Django que la "URL" de los media es la misma que donde están tus fotos estáticas
    # Si tus fotos están en static/assets/images/..., la URL web es /static/assets/images/...
    MEDIA_URL = '/static/assets/images/'
    
    # Para que WhiteNoise sepa que también queremos servir cosas que vengan de media (por si acaso)
    WHITENOISE_ROOT = os.path.join(BASE_DIR, 'app/static/assets/images')
