# Generated by Django 5.2.7 on 2025-10-27 12:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Pirineo Catalán, Pirineo Aragonés, Cordillera Cantábrica', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name_plural': 'Localizaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoPista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('verde', 'Verde - Principiante'), ('azul', 'Azul - Fácil'), ('roja', 'Roja - Intermedia'), ('negra', 'Negra - Difícil')], max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Características y nivel de dificultad', null=True)),
                ('nivel_dificultad', models.IntegerField(default=1, help_text='Nivel de dificultad del 1 (más fácil) al 5 (más difícil)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Tipo de Pista',
                'verbose_name_plural': 'Tipos de Pista',
                'ordering': ['nivel_dificultad'],
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Baqueira Beret, Formigal', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(decimal_places=6, help_text='Latitud en formato decimal', max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, help_text='Longitud en formato decimal', max_digits=9)),
                ('km_pistas_totales', models.DecimalField(decimal_places=2, help_text='Kilómetros totales de pistas', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('altitud_minima', models.IntegerField(help_text='Altitud mínima en metros', validators=[django.core.validators.MinValueValidator(0)])),
                ('altitud_maxima', models.IntegerField(help_text='Altitud máxima en metros', validators=[django.core.validators.MinValueValidator(0)])),
                ('numero_remontes', models.IntegerField(default=0, help_text='Número total de remontes mecánicos', validators=[django.core.validators.MinValueValidator(0)])),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('imagen_portada', models.URLField(blank=True, help_text='URL de la imagen principal', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('localizacion', models.ForeignKey(help_text='Región donde se encuentra la estación', on_delete=django.db.models.deletion.PROTECT, related_name='estaciones', to='app.localizacion')),
            ],
            options={
                'verbose_name': 'Estación',
                'verbose_name_plural': 'Estaciones',
                'ordering': ['-km_pistas_totales'],
            },
        ),
        migrations.CreateModel(
            name='PistaEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, help_text='Número de pistas de este tipo', validators=[django.core.validators.MinValueValidator(0)])),
                ('km_totales', models.DecimalField(decimal_places=2, default=0, help_text='Kilómetros totales de este tipo de pista', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas_detalle', to='app.estacion')),
                ('tipo_pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas_detalle', to='app.tipopista')),
            ],
            options={
                'verbose_name': 'Pista por Estación',
                'verbose_name_plural': 'Pistas por Estación',
                'ordering': ['tipo_pista__nivel_dificultad'],
                'unique_together': {('estacion', 'tipo_pista')},
            },
        ),
        migrations.AddField(
            model_name='estacion',
            name='tipos_pista',
            field=models.ManyToManyField(help_text='Tipos de pistas disponibles', related_name='estaciones', through='app.PistaEstacion', to='app.tipopista'),
        ),
    ]
