# Generated by Django 5.2.7 on 2025-11-22 17:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localizacion',
            options={'verbose_name': 'Localización', 'verbose_name_plural': 'Localizaciones'},
        ),
        migrations.AddField(
            model_name='localizacion',
            name='imagen_portada',
            field=models.ImageField(blank=True, help_text='Imagen Principal', null=True, upload_to='portadas/', verbose_name='Imagen de portada'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='altitud_maxima',
            field=models.IntegerField(help_text='Altitud máxima en metros', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Altitud máxima'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='altitud_minima',
            field=models.IntegerField(help_text='Altitud mínima en metros', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Altitud mínima'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='imagen_portada',
            field=models.ImageField(blank=True, help_text='Imagen Principal', null=True, upload_to='portadas/', verbose_name='Imagen de portada'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='km_pistas_totales',
            field=models.DecimalField(decimal_places=2, help_text='Kilómetros totales de pistas', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Km de pistas totales'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='latitud',
            field=models.DecimalField(decimal_places=6, help_text='Latitud en formato decimal', max_digits=9, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='localizacion',
            field=models.ForeignKey(help_text='Región donde se encuentra la estación', on_delete=django.db.models.deletion.PROTECT, related_name='estaciones', to='app.localizacion', verbose_name='Localización'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='longitud',
            field=models.DecimalField(decimal_places=6, help_text='Longitud en formato decimal', max_digits=9, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nombre',
            field=models.CharField(help_text='Ej: Baqueira Beret, Formigal', max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='numero_remontes',
            field=models.IntegerField(default=0, help_text='Número total de remontes mecánicos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de remontes'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='tipos_pista',
            field=models.ManyToManyField(help_text='Tipos de pistas disponibles', related_name='estaciones', through='app.PistaEstacion', to='app.tipopista', verbose_name='Tipos de pista'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='pistaestacion',
            name='cantidad',
            field=models.IntegerField(default=0, help_text='Número de pistas de este tipo', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='pistaestacion',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas_detalle', to='app.estacion', verbose_name='Estación'),
        ),
        migrations.AlterField(
            model_name='pistaestacion',
            name='km_totales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Kilómetros totales de este tipo de pista', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Km totales'),
        ),
        migrations.AlterField(
            model_name='pistaestacion',
            name='tipo_pista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas_detalle', to='app.tipopista', verbose_name='Tipo de pista'),
        ),
        migrations.AlterField(
            model_name='tipopista',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Características y nivel de dificultad', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipopista',
            name='nivel_dificultad',
            field=models.IntegerField(default=1, help_text='Nivel de dificultad del 1 (más fácil) al 5 (más difícil)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nivel de dificultad'),
        ),
        migrations.AlterField(
            model_name='tipopista',
            name='nombre',
            field=models.CharField(choices=[('verde', 'Verde - Principiante'), ('azul', 'Azul - Fácil'), ('roja', 'Roja - Intermedia'), ('negra', 'Negra - Difícil')], max_length=20, unique=True, verbose_name='Color / Tipo'),
        ),
    ]
